### ISSUE TITLE
Random_seed feature request

### ISSUE THREAD

**Issue by Peter-Vincent** [wl17443/neuronmodelling#2]
### Desired behaviour

We should have the option to run the same simulation, with the same parameters, and reliably get the same result back, or to re-run with different random seeds

### Current behaviour

At the moment I can run the same simulation and sometimes get exactly the same behaviour, sometimes its different. 

### To-do

Somewhere in the code, where the randomness is being introduced, please add an setting/option/decorator that lets us run the simulation with the same random seed. 

### Demontration below
![base_truth2](https://user-images.githubusercontent.com/45718646/91637435-4a8ee600-ea00-11ea-9d59-cda3b03334c7.png)
![base_truth3](https://user-images.githubusercontent.com/45718646/91637436-4b277c80-ea00-11ea-8729-8de4a1b351c4.png)

**Comment by stebett** [comment]
The only random element is noise, defined in lif_model. 
Anyway, I think it is simpler to just add a seed to the ring class.

After commit 46448d4fb6256fea9c93f2768e45ae3161e09f45 the behavior is the following:

![29-08-2020, 15:53:14](https://user-images.githubusercontent.com/46384690/91638404-b9c00680-ea0f-11ea-9156-dfa58ae2b39c.png)
![29-08-2020, 15:53:03](https://user-images.githubusercontent.com/46384690/91638405-baf13380-ea0f-11ea-921a-e745bd278f43.png)
![29-08-2020, 15:52:48](https://user-images.githubusercontent.com/46384690/91638406-bb89ca00-ea0f-11ea-9ed1-88edcf4b9279.png)
![29-08-2020, 15:52:36](https://user-images.githubusercontent.com/46384690/91638407-bc226080-ea0f-11ea-9ce4-dd399f52bdac.png)

**Comment by Peter-Vincent** [comment]
Great, that's perfect!
